### ISSUE TITLE
BaseActivity

### ISSUE THREAD

**Issue by mohamedebrahim96** [armcha/MVP-Architecture-Components#2]
your project understandable but where base activity 
why did you put it away 

-------------------------------

![default](https://user-images.githubusercontent.com/16405013/45010078-d0434b00-b00b-11e8-953c-3715d8533e30.JPG)

**Comment by armcha** [comment]
@mohamedebrahim96 Please see there, it is in the separate module
https://github.com/armcha/MVP-Architecture-Components/blob/master/arch/src/main/java/com/luseen/arch/BaseActivity.java
